name: gold-price-daily

on:
  workflow_dispatch:
  schedule:
    - cron: '05 21 * * *'

jobs:
  schedule_pipelines:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: install python packages
        run: |
          cd src
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter
          pip install jupyter nbconvert
          pip install hopsworks[python] pyarrow

      - name: execute python workflows from bash script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          cd src
          jupyter nbconvert --to notebook --execute 3_gold_prices_feature_pipeline.ipynb
          jupyter nbconvert --to notebook --execute 5_gold_prices_batch_inference.ipynb

      - name: github pages publish
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Gold Price Dashboard published"
          commit_options: '--no-verify --signoff'

          file_pattern: 'docs/goldPrice/assets/img/* docs/_includes/*'

          repository: .

          status_options: '--untracked-files=no'

          skip_dirty_check: true

          skip_fetch: true

          skip_checkout: true

          push_options: '--force'
